### ISSUE TITLE
Add "Path Problems in Networks" to the collection.

### ISSUE THREAD

**Issue by gsvgit** [szarnyasg/graphblas-pointers#2]
Hello.

Do you know about ["Path Problems in Networks"](https://www.semanticscholar.org/paper/Path-Problems-in-Networks-Baras-Theodorakopoulos/0fae6d70a155e78592e65c1f589274bfee64f323)? Looks relevant to GraphBLAS because describe a unified semiring-based framework for network (graph) analysis. Moreover, it contains a big number of concrete semirings and related applications. I guess it may be interesting for GraphBLAS community and should be included in the pointers collection.

**Comment by szarnyasg** [comment]
I wasn't aware of this but it looks good. Could you please open a PR to the repository?

**Comment by gsvgit** [comment]
Sure. Done: #3
